sudo: false
language: python

python:
    - "3.4"
  
before_install:
    - pip install flake8 --use-mirrors
    - pip install codecov
    - make flake

install:
    - make install-test
    - pip install coveralls

script:
    - make coveralls

after_success:
    - coveralls
    - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837fe61b536818b676ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
